### ISSUE TITLE
firefox 71 lost shadowfox

### ISSUE THREAD

**Issue by quaimodo2012** [overdodactyl/userContent-tweaks#299]

**Comment by justbispo** [comment]
Since Firefox v69, the loading of `userChrome.css` and `userContent.css` is disabled by default. You need to follow this steps: [https://www.reddit.com/r/FirefoxCSS/comments/brmi8v/psa_firefox_v69_users_will_have_to_set_a_pref_to/](https://www.reddit.com/r/FirefoxCSS/comments/brmi8v/psa_firefox_v69_users_will_have_to_set_a_pref_to/)

**Comment by quaimodo2012** [comment]
that fixed it right up thanks a million.
