### ISSUE TITLE
uBlock Origin dynamic filtering menu is not dark

### ISSUE THREAD

**Issue by SakhG** [overdodactyl/userContent-tweaks#306]
* uBlock Origin 1.25.0
* Firefox 73.0.1 x64 stable
* Windows 10
* I installed ShadowFox a long time ago and it was great but something happened recently (browser/addon updated) and it became like that
* <details>
  <summary>Screenshot</summary>
  
  ![image](https://user-images.githubusercontent.com/10335530/75631350-1c9b2700-5bc0-11ea-81df-5afe3b36a880.png)
  
</details>

*  Only this is an issue, every other addon/menu are correctly dark

*  I tried reinstalling with no result

**Comment by stonecrusher** [comment]
It's fixed in the PR https://github.com/stonecrusher/ShadowFox/blob/patch-1/css/userContent-files/webextension-tweaks/ublock_origin.css but not merged yet. The original author abandoned this project for a year now :-/
Fix it manually with the link provided or wait for the project to come alive again.

**Comment by SakhG** [comment]
I'm suppose to put this in `*User*\AppData\Roaming\Mozilla\Firefox\Profiles\*profile*\chrome\ShadowFox_customization\userContent_customization.css` , correct?
Then I just need to run the updater right?

**Comment by stonecrusher** [comment]
No.
Meanwhile a new uBO design arrived and we don't have a dark theme for that yet.
Actually we're waiting for the official one to be released.
https://github.com/overdodactyl/ShadowFox/issues/310
