### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by moonlitglare** [overdodactyl/userContent-tweaks#342]
Is this being worked on anymore?

**Comment by gianpaj** [comment]
looks like it's not but it worked for me on Firefox 92 on macOS using https://github.com/arguablykomodo/shadowfox-updater

**Comment by brsk93** [comment]
> 
> 
> Is this being worked on anymore?

Unfortunately I think it's dead.
A shame, because I still have to find a theme that's even a fraction of how good and comprehensive this one was.
You can still sorta use it if you're willing to fix a bunch of things, but it stopped being worth it for me a while ago. Now I'm just using bits and pieces of it to style addons and whatever the native dark theme is still missing.

**Comment by Movisivi** [comment]
Dead for good reasons, no need for this anymore. Firefox already has a complete dark theme
